In [3]:
import pandas as pd

In [39]:
df=pd.read_csv('Business_Attributes_Final.csv')
df.head()

C:\Users\manis\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,attributes.AcceptsInsurance,attributes.Alcohol,attributes.Ambience,attributes.BYOB,attributes.BestNights,attributes.BikeParking,attributes.BusinessAcceptsBitcoin,attributes.BusinessAcceptsCreditCards,attributes.BusinessParking,attributes.ByAppointmentOnly,...,attributes.RestaurantsDelivery,attributes.RestaurantsGoodForGroups,attributes.RestaurantsPriceRange2,attributes.RestaurantsReservations,attributes.RestaurantsTableService,attributes.RestaurantsTakeOut,attributes.Smoking,attributes.WheelchairAccessible,attributes.WiFi,business_id
0,NaN,'beer_and_wine',"{'touristy': False, 'hipster': False, 'romanti...",NaN,NaN,True,False,True,"{'garage': False, 'street': True, 'validated':...",NaN,...,None,True,2,False,True,True,NaN,True,u'free',6iYb2HFDywm3zjuRg0shjw
1,NaN,u'beer_and_wine',"{'romantic': False, 'intimate': False, 'touris...",NaN,NaN,False,NaN,True,"{'garage': True, 'street': False, 'validated':...",False,...,False,False,2,False,NaN,True,NaN,NaN,u'free',tCbdrRPZA0oiIYSmHG3J0w
2,NaN,NaN,NaN,NaN,NaN,False,NaN,True,"{'garage': False, 'street': True, 'validated':...",False,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,bvN78flM8NLprQ1a1y5dRg
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,oaepsyvc0J17qwi8cfrOWg
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,"{'garage': False, 'street': False, 'validated'...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PE9uqAjdw0E4-8mjGl3wVA

In [40]:
df_flt = df[df['attributes.Ambience'].notna()]

In [ ]:
df_flt['attributes.Ambience'] = df_flt['attributes.Ambience'].apply(lambda x: eval(x))

In [51]:
data = [df_flt['attributes.Ambience'], df_flt['business_id']]

headers = ["attributes_Ambience", "business_id"]

df3 = pd.concat(data, axis=1, keys=headers)

In [57]:
type(df3['business_id'][0])

df3.shape

(43882, 2)

In [80]:
df3.dropna(inplace=True)

In [66]:
out = df3.to_json(orient='records')[1:-1].replace('},{', '} {')

In [85]:
import json
count = 0
final_data = []
for index, row in df3.iterrows():
    temp_dict = row['attributes_Ambience']
    temp_dict['business_id_orig'] = row['business_id']
    final_data.append(temp_dict)

with open('Business_Ambience_Attributes.json', 'a') as outfile:
    json.dump(final_data, outfile, indent=2)